version: 2

lang: "en"
format:
  senderChatFormat: "&f[&7me &f => &7 {target}&f]&7: &r{message}"
  targetChatFormat: "&f[&7{sender} &f => &7 me&f]&7: &r{message}"
  spyChatFormat: "&f[&7{sender} &f => &7 {target}&f]&7: &r{message}"

# Sound played to the receiver of a private message.
notification:
  enabled: true
  sound: "entity.experience_orb.pickup"
